# Generated by Django 6.0.5 on 2026-05-28 06:11

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del premio')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio en soles virtuales')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Pon 0 si es ilimitado (Yape, sorteos, etc.)', verbose_name='Stock disponible (0 = ilimitado)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden de aparicion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Soles descontados')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de revision'), ('approved', 'Aprobado — entregado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('phone', models.CharField(max_length=20, verbose_name='Celular / Yape')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('district', models.CharField(max_length=100, verbose_name='Distrito')),
                ('address', models.TextField(verbose_name='Direccion completa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas del admin')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='store.storeitem', verbose_name='Premio')),
            ],
            options={
                'verbose_name': 'Solicitud de canje',
                'verbose_name_plural': 'Solicitudes de canje',
                'ordering': ['-created_at'],
            },
        ),
    ]
