# Generated by Django 6.0.5 on 2026-05-21 22:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0003_initial_bets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('block_qualifier', 'Clasificado de Bloque'), ('champion', 'Campeon de Final')], max_length=30)),
                ('group_name', models.CharField(max_length=200, verbose_name='Nombre agrupacion')),
                ('group_logo', models.ImageField(blank=True, null=True, upload_to='bet_logos/')),
                ('odds', models.DecimalField(decimal_places=2, default=Decimal('1.53'), max_digits=5, verbose_name='Cuota')),
                ('is_resolved', models.BooleanField(default=False)),
                ('won', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.block', verbose_name='Bloque')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_options', to='contests.contest')),
            ],
            options={
                'verbose_name': 'Opcion de Apuesta',
                'verbose_name_plural': 'Opciones de Apuesta',
                'ordering': ['bet_type', 'block__order', 'odds'],
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto apostado')),
                ('odds_at_bet', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cuota al apostar')),
                ('potential_win', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganancia potencial')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('won', 'Ganada'), ('lost', 'Perdida')], default='pending', max_length=10)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='bets.betoption')),
            ],
            options={
                'verbose_name': 'Apuesta',
                'verbose_name_plural': 'Apuestas',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('total_won', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_lost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billetera',
                'verbose_name_plural': 'Billeteras',
            },
        ),
    ]
