# Generated by Django 6.0.5 on 2026-05-23 04:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial_bets'),
        ('contests', '0005_alter_finalresult_options_alter_block_contest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bet',
            name='odds_at_bet',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bet',
            name='potential_win',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='betoption',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.block'),
        ),
        migrations.AlterField(
            model_name='betoption',
            name='group_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='betoption',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='betoption',
            name='odds',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.53'), max_digits=5),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'status'], name='bets_bet_user_id_f8a082_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['option', 'status'], name='bets_bet_option__e3670a_idx'),
        ),
        migrations.AddIndex(
            model_name='betoption',
            index=models.Index(fields=['contest', 'bet_type', 'is_active', 'is_resolved'], name='bets_betopt_contest_e84e6c_idx'),
        ),
    ]
