# Generated by Django 6.0.5 on 2026-05-21 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='URL amigable')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='flyers/', verbose_name='Flyer')),
                ('location', models.CharField(max_length=200, verbose_name='Lugar')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('status', models.CharField(choices=[('upcoming', 'Proximo'), ('active', 'En Curso'), ('finished', 'Finalizado')], default='upcoming', max_length=20, verbose_name='Estado')),
                ('judges_count', models.PositiveIntegerField(default=5, verbose_name='Cantidad de jurados')),
                ('qualifiers_per_block', models.PositiveIntegerField(default=2, verbose_name='Clasificados por bloque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del bloque')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_final', models.BooleanField(default=False, verbose_name='Es final')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='contests.contest', verbose_name='Concurso')),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='Nombre agrupacion')),
                ('group_logo', models.ImageField(blank=True, null=True, upload_to='final_logos/', verbose_name='Logo')),
                ('position', models.PositiveIntegerField(verbose_name='Posicion final')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Puntaje total')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='contests.contest', verbose_name='Concurso')),
            ],
            options={
                'verbose_name': 'Resultado Final',
                'verbose_name_plural': 'Resultados Finales',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre agrupacion')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden de presentacion')),
                ('qualified', models.BooleanField(default=False, verbose_name='Clasificado')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='contests.block', verbose_name='Bloque')),
            ],
            options={
                'verbose_name': 'Agrupacion',
                'verbose_name_plural': 'Agrupaciones',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del jurado')),
                ('judge_number', models.PositiveIntegerField(verbose_name='Numero de jurado')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='contests.contest', verbose_name='Concurso')),
            ],
            options={
                'verbose_name': 'Jurado',
                'verbose_name_plural': 'Jurados',
                'ordering': ['judge_number'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_number', models.PositiveIntegerField(verbose_name='Numero de jurado')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Puntaje')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='contests.group', verbose_name='Agrupacion')),
            ],
            options={
                'verbose_name': 'Puntaje',
                'verbose_name_plural': 'Puntajes',
                'unique_together': {('group', 'judge_number')},
            },
        ),
    ]
