# Generated by Django 6.0.5 on 2026-05-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['judge_number'], 'verbose_name': 'Puntaje', 'verbose_name_plural': 'Puntajes'},
        ),
        migrations.AlterField(
            model_name='contest',
            name='judges_count',
            field=models.PositiveIntegerField(default=4, verbose_name='Cantidad de jurados'),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='total_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntaje total'),
        ),
        migrations.AlterField(
            model_name='score',
            name='judge_number',
            field=models.PositiveIntegerField(verbose_name='Jurado N°'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntaje'),
        ),
    ]
