# Generated by Django 6.0.5 on 2026-05-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_score_to_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='final_judges_count',
            field=models.PositiveIntegerField(default=4, verbose_name='Cantidad de jurados (final)'),
        ),
        migrations.AlterField(
            model_name='block',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='Es bloque final'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='judges_count',
            field=models.PositiveIntegerField(default=4, verbose_name='Cantidad de jurados (bloques)'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Proximo'), ('active', 'En Curso'), ('final', 'En Final'), ('finished', 'Finalizado')], default='upcoming', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='total_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntaje total en final'),
        ),
        migrations.AlterField(
            model_name='score',
            name='judge_number',
            field=models.PositiveIntegerField(verbose_name='Jurado N'),
        ),
    ]
