# Generated by Django 6.0.5 on 2026-05-22 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_initial_bets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalresult',
            options={'ordering': ['position'], 'verbose_name': 'Resultado Final (Podio)', 'verbose_name_plural': 'Podio Final'},
        ),
        migrations.AlterField(
            model_name='contest',
            name='final_judges_count',
            field=models.PositiveIntegerField(default=4, verbose_name='Jurados en final'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='judges_count',
            field=models.PositiveIntegerField(default=4, verbose_name='Jurados en bloques'),
        ),
        migrations.CreateModel(
            name='FinalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='final_logos/', verbose_name='Logo')),
                ('final_order', models.PositiveIntegerField(default=1, verbose_name='Orden en final (sorteo)')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_groups', to='contests.contest', verbose_name='Concurso')),
                ('source_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_entries', to='contests.group', verbose_name='Agrupacion origen')),
            ],
            options={
                'verbose_name': 'Agrupacion en Final',
                'verbose_name_plural': 'Tabla Final',
                'ordering': ['final_order'],
                'unique_together': {('contest', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_number', models.PositiveIntegerField(verbose_name='Jurado N')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Puntaje')),
                ('final_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_scores', to='contests.finalgroup', verbose_name='Agrupacion en final')),
            ],
            options={
                'verbose_name': 'Puntaje Final',
                'verbose_name_plural': 'Puntajes Final',
                'ordering': ['judge_number'],
                'unique_together': {('final_group', 'judge_number')},
            },
        ),
    ]
