# Generated by Django 6.0.5 on 2026-05-23 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_add_finalgroup_finalscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalresult',
            options={'ordering': ['position'], 'verbose_name': 'Resultado Final', 'verbose_name_plural': 'Podio Final'},
        ),
        migrations.AlterField(
            model_name='block',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='contests.contest'),
        ),
        migrations.AlterField(
            model_name='block',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contest',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='flyers/'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Proximo'), ('active', 'En Curso'), ('final', 'En Final'), ('finished', 'Finalizado')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='finalgroup',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_groups', to='contests.contest'),
        ),
        migrations.AlterField(
            model_name='finalgroup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='final_logos/'),
        ),
        migrations.AlterField(
            model_name='finalgroup',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='finalgroup',
            name='source_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_entries', to='contests.group'),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_results', to='contests.contest'),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='group_logo',
            field=models.ImageField(blank=True, null=True, upload_to='final_logos/'),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='group_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='position',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='final_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_scores', to='contests.finalgroup'),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='judge_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='finalscore',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='contests.block'),
        ),
        migrations.AlterField(
            model_name='group',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='contests.contest'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='judge_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='judge',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='score',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='contests.group'),
        ),
        migrations.AlterField(
            model_name='score',
            name='judge_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
