# Generated by Django 6.0.5 on 2026-05-28 07:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_alter_finalresult_options_alter_block_contest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='flyer',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='flyer'),
        ),
        migrations.AlterField(
            model_name='finalgroup',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='group_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='group_logo'),
        ),
        migrations.AlterField(
            model_name='group',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
